"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class detection_robots_tracked(object):

    __slots__ = ["robot_id", "position_x", "position_y", "vel_x", "vel_y", "vel_angular", "orientation"]

    __typenames__ = ["int16_t", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self):
        self.robot_id = 0
        """ LCM Type: int16_t """
        self.position_x = 0.0
        """
        robot_id is the combination of a team and a robot id
        LCM Type: float
        """

        self.position_y = 0.0
        """
        mm
        LCM Type: float
        """

        self.vel_x = 0.0
        """
        mm
        LCM Type: float
        """

        self.vel_y = 0.0
        """
        The velocity [mm/s] in the ssl-vision coordinate system
        LCM Type: float
        """

        self.vel_angular = 0.0
        """ LCM Type: float """
        self.orientation = 0.0
        """
        The angular velocity [rad/s] in the ssl-vision coordinate system
        LCM Type: float
        """


    def encode(self):
        buf = BytesIO()
        buf.write(detection_robots_tracked._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hffffff", self.robot_id, self.position_x, self.position_y, self.vel_x, self.vel_y, self.vel_angular, self.orientation))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != detection_robots_tracked._get_packed_fingerprint():
            raise ValueError("Decode error")
        return detection_robots_tracked._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = detection_robots_tracked()
        self.robot_id, self.position_x, self.position_y, self.vel_x, self.vel_y, self.vel_angular, self.orientation = struct.unpack(">hffffff", buf.read(26))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if detection_robots_tracked in parents: return 0
        tmphash = (0xcde03e1163900431) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if detection_robots_tracked._packed_fingerprint is None:
            detection_robots_tracked._packed_fingerprint = struct.pack(">Q", detection_robots_tracked._get_hash_recursive([]))
        return detection_robots_tracked._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", detection_robots_tracked._get_packed_fingerprint())[0]

