/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen 1.5.1
 **/

#ifndef __data_vision_hpp__
#define __data_vision_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "detection_robots.hpp"
#include "detection_robots.hpp"
#include "detection_balls.hpp"
#include "detection_geometry.hpp"

namespace data
{

/// main struct
class vision
{
    public:
        int64_t    timestamp;

        int16_t    robots_yellow_size;

        int16_t    robots_blue_size;

        /**
         * LCM Type: data.detection_robots[robots_yellow_size]
         */
        std::vector< data::detection_robots > robots_yellow;

        /**
         * LCM Type: data.detection_robots[robots_blue_size]
         */
        std::vector< data::detection_robots > robots_blue;

        data::detection_balls balls;

        data::detection_geometry field;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "vision"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int vision::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int vision::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int vision::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t vision::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* vision::getTypeName()
{
    return "vision";
}

int vision::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->robots_yellow_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->robots_blue_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->robots_yellow_size; a0++) {
        tlen = this->robots_yellow[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->robots_blue_size; a0++) {
        tlen = this->robots_blue[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->balls._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->field._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int vision::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->robots_yellow_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->robots_blue_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->robots_yellow.resize(this->robots_yellow_size);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->robots_yellow_size; a0++) {
        tlen = this->robots_yellow[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    try {
        this->robots_blue.resize(this->robots_blue_size);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->robots_blue_size; a0++) {
        tlen = this->robots_blue[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->balls._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->field._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int vision::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->robots_yellow_size; a0++) {
        enc_size += this->robots_yellow[a0]._getEncodedSizeNoHash();
    }
    for (int a0 = 0; a0 < this->robots_blue_size; a0++) {
        enc_size += this->robots_blue[a0]._getEncodedSizeNoHash();
    }
    enc_size += this->balls._getEncodedSizeNoHash();
    enc_size += this->field._getEncodedSizeNoHash();
    return enc_size;
}

uint64_t vision::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == vision::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, vision::getHash };

    uint64_t hash = 0xb27b48fcf3d90b9bLL +
         data::detection_robots::_computeHash(&cp) +
         data::detection_robots::_computeHash(&cp) +
         data::detection_balls::_computeHash(&cp) +
         data::detection_geometry::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
