"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class detection_balls(object):

    __slots__ = ["position_x", "position_y"]

    __typenames__ = ["float", "float"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.position_x = 0.0
        """ LCM Type: float """
        self.position_y = 0.0
        """
        mm
        LCM Type: float
        """


    def encode(self):
        buf = BytesIO()
        buf.write(detection_balls._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ff", self.position_x, self.position_y))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != detection_balls._get_packed_fingerprint():
            raise ValueError("Decode error")
        return detection_balls._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = detection_balls()
        self.position_x, self.position_y = struct.unpack(">ff", buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if detection_balls in parents: return 0
        tmphash = (0x9227b9fea982bc1f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if detection_balls._packed_fingerprint is None:
            detection_balls._packed_fingerprint = struct.pack(">Q", detection_balls._get_hash_recursive([]))
        return detection_balls._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", detection_balls._get_packed_fingerprint())[0]

