"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import data

class vision(object):
    """ main struct """

    __slots__ = ["timestamp", "robots_yellow_size", "robots_blue_size", "robots_yellow", "robots_blue", "balls", "field"]

    __typenames__ = ["int64_t", "int16_t", "int16_t", "data.detection_robots", "data.detection_robots", "data.detection_balls", "data.detection_geometry"]

    __dimensions__ = [None, None, None, ["robots_yellow_size"], ["robots_blue_size"], None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.robots_yellow_size = 0
        """ LCM Type: int16_t """
        self.robots_blue_size = 0
        """ LCM Type: int16_t """
        self.robots_yellow = []
        """ LCM Type: data.detection_robots[robots_yellow_size] """
        self.robots_blue = []
        """ LCM Type: data.detection_robots[robots_blue_size] """
        self.balls = data.detection_balls()
        """ LCM Type: data.detection_balls """
        self.field = data.detection_geometry()
        """ LCM Type: data.detection_geometry """

    def encode(self):
        buf = BytesIO()
        buf.write(vision._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhh", self.timestamp, self.robots_yellow_size, self.robots_blue_size))
        for i0 in range(self.robots_yellow_size):
            assert self.robots_yellow[i0]._get_packed_fingerprint() == data.detection_robots._get_packed_fingerprint()
            self.robots_yellow[i0]._encode_one(buf)
        for i0 in range(self.robots_blue_size):
            assert self.robots_blue[i0]._get_packed_fingerprint() == data.detection_robots._get_packed_fingerprint()
            self.robots_blue[i0]._encode_one(buf)
        assert self.balls._get_packed_fingerprint() == data.detection_balls._get_packed_fingerprint()
        self.balls._encode_one(buf)
        assert self.field._get_packed_fingerprint() == data.detection_geometry._get_packed_fingerprint()
        self.field._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vision._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vision._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = vision()
        self.timestamp, self.robots_yellow_size, self.robots_blue_size = struct.unpack(">qhh", buf.read(12))
        self.robots_yellow = []
        for i0 in range(self.robots_yellow_size):
            self.robots_yellow.append(data.detection_robots._decode_one(buf))
        self.robots_blue = []
        for i0 in range(self.robots_blue_size):
            self.robots_blue.append(data.detection_robots._decode_one(buf))
        self.balls = data.detection_balls._decode_one(buf)
        self.field = data.detection_geometry._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if vision in parents: return 0
        newparents = parents + [vision]
        tmphash = (0xb27b48fcf3d90b9b+ data.detection_robots._get_hash_recursive(newparents)+ data.detection_robots._get_hash_recursive(newparents)+ data.detection_balls._get_hash_recursive(newparents)+ data.detection_geometry._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if vision._packed_fingerprint is None:
            vision._packed_fingerprint = struct.pack(">Q", vision._get_hash_recursive([]))
        return vision._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", vision._get_packed_fingerprint())[0]

